# Generated by Django 4.2.2 on 2023-07-01 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='form_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.SmallIntegerField(default=10)),
                ('logradouro', models.CharField(max_length=200)),
                ('livro_emplacamento', models.CharField(max_length=200)),
                ('responsavel', models.CharField(max_length=200)),
                ('dt_realizacao', models.DateField()),
                ('observacao', models.CharField(max_length=200)),
            ],
        ),
    ]
