# Generated by Django 4.2.2 on 2023-07-02 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tabelaoapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='form_table',
            name='index',
        ),
    ]
