# Generated by Django 4.2.2 on 2023-07-02 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tabelaoapp', '0002_remove_form_table_index'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form_table',
            name='livro_emplacamento',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='form_table',
            name='observacao',
            field=models.CharField(max_length=1000),
        ),
    ]
