# Generated by Django 4.2.2 on 2023-07-02 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tabelaoapp', '0003_alter_form_table_livro_emplacamento_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form_table',
            name='dt_realizacao',
            field=models.CharField(max_length=200),
        ),
    ]
